#!/bin/bash

#PBS -l nodes=16:ppn=8
#PBS -l walltime=00:02:00

PROC=128

#PBS -N 16ProcsTesting
#PBS -e 16procsv3.%PBS_JOBID.err
#PBS -o 16procsv3.%PBS_JOBID.out

cd /user/hquang/cs442/watch-that-wheeler-route

module load gcc
module load openmpi/4.1.2-q2zi

mpirun -n $PROC ./main
